import { Issue } from './types';

export const issues: Issue[] = [
  {
    id: 'PRT-20481',
    title: 'Open drain near Government College',
    category: 'Drainage',
    location: 'Government College Road',
    ward: 'Ward 7',
    mapX: 55, mapY: 38,
    lat: 25.8784, lng: 81.9723,
    status: 'in-progress',
    slaDuration: '24h',
    slaRemaining: '08h 32m',
    slaBreached: false,
    reportedDate: '2026-08-17',
    reportedTime: '09:14',
    department: 'Public Works Department',
    confirmations: 47,
    upvotes: 156,
    severity: 'high',
    description: 'Open drainage channel near Government Degree College main gate causing foul smell and waterlogging on the footpath. Multiple citizens affected.',
    relatedReports: 4,
    reportedBy: 'Ramesh Chandra Verma',
  },
  {
    id: 'PRT-20476',
    title: 'Pothole on Station Road',
    category: 'Roads & Potholes',
    location: 'Station Road, near Petrol Pump',
    ward: 'Ward 3',
    mapX: 38, mapY: 32,
    lat: 25.8742, lng: 81.9681,
    status: 'pending',
    slaDuration: '48h',
    slaRemaining: '02h 15m',
    slaBreached: false,
    reportedDate: '2026-08-16',
    reportedTime: '14:30',
    department: 'PWD Roads Division',
    confirmations: 23,
    upvotes: 89,
    severity: 'medium',
    description: 'Large pothole approximately 2ft wide on Station Road near the petrol pump causing vehicle damage and traffic disruption.',
    relatedReports: 2,
    reportedBy: 'Sunita Mishra',
  },
  {
    id: 'PRT-20471',
    title: 'Garbage accumulation near Civil Lines',
    category: 'Garbage',
    location: 'Civil Lines Main Road',
    ward: 'Ward 5',
    mapX: 68, mapY: 22,
    lat: 25.8810, lng: 81.9748,
    status: 'sla-breached',
    slaDuration: '12h',
    slaRemaining: 'Breached',
    slaBreached: true,
    reportedDate: '2026-08-15',
    reportedTime: '07:45',
    department: 'Sanitation Division',
    confirmations: 61,
    upvotes: 234,
    severity: 'critical',
    description: 'Large garbage dump in front of Civil Lines park. Uncollected for over 3 days causing health hazard.',
    relatedReports: 6,
    reportedBy: 'Ajay Kumar Singh',
  },
  {
    id: 'PRT-20465',
    title: 'Broken streetlight near Bus Stand',
    category: 'Streetlights',
    location: 'Bus Stand, Main Road',
    ward: 'Ward 2',
    mapX: 28, mapY: 52,
    lat: 25.8758, lng: 81.9650,
    status: 'resolved',
    slaDuration: '24h',
    slaRemaining: 'Resolved',
    slaBreached: false,
    reportedDate: '2026-08-14',
    reportedTime: '20:00',
    department: 'Electrical Division',
    confirmations: 18,
    upvotes: 45,
    severity: 'low',
    description: 'Street light pole near Bus Stand entrance not working for 3 days causing safety concerns at night.',
    relatedReports: 1,
    reportedBy: 'Priya Sharma',
  },
  {
    id: 'PRT-20459',
    title: 'Water leakage near Market Road',
    category: 'Water',
    location: 'Market Road, Ward 4 Junction',
    ward: 'Ward 4',
    mapX: 48, mapY: 58,
    lat: 25.8720, lng: 81.9702,
    status: 'in-progress',
    slaDuration: '24h',
    slaRemaining: '14h 20m',
    slaBreached: false,
    reportedDate: '2026-08-13',
    reportedTime: '11:20',
    department: 'Jal Nigam',
    confirmations: 32,
    upvotes: 112,
    severity: 'high',
    description: 'Water pipe leakage at Market Road junction causing road flooding and significant water waste.',
    relatedReports: 3,
    reportedBy: 'Vikash Dubey',
  },
  {
    id: 'PRT-20452',
    title: 'Road cave-in near Collectorate',
    category: 'Roads & Potholes',
    location: 'Collectorate Road',
    ward: 'Ward 1',
    mapX: 72, mapY: 15,
    lat: 25.8830, lng: 81.9780,
    status: 'assigned',
    slaDuration: '48h',
    slaRemaining: '28h 45m',
    slaBreached: false,
    reportedDate: '2026-08-18',
    reportedTime: '08:00',
    department: 'PWD Roads Division',
    confirmations: 12,
    upvotes: 67,
    severity: 'high',
    description: 'Significant road cave-in near Collectorate office affecting two-way traffic.',
    relatedReports: 2,
    reportedBy: 'Mohan Lal Gupta',
  },
  {
    id: 'PRT-20448',
    title: 'Choked drainage near Parade Ground',
    category: 'Drainage',
    location: 'Parade Ground Area',
    ward: 'Ward 8',
    mapX: 22, mapY: 68,
    lat: 25.8695, lng: 81.9635,
    status: 'pending',
    slaDuration: '24h',
    slaRemaining: '16h 10m',
    slaBreached: false,
    reportedDate: '2026-08-18',
    reportedTime: '10:30',
    department: 'Public Works Department',
    confirmations: 8,
    upvotes: 38,
    severity: 'medium',
    description: 'Drainage choked near Parade Ground causing waterlogging after rain.',
    relatedReports: 1,
    reportedBy: 'Kavita Tripathi',
  },
];

export const wardStats = [
  { ward: 'Ward 1', total: 18, resolved: 14 },
  { ward: 'Ward 2', total: 25, resolved: 20 },
  { ward: 'Ward 3', total: 31, resolved: 22 },
  { ward: 'Ward 4', total: 22, resolved: 18 },
  { ward: 'Ward 5', total: 45, resolved: 28 },
  { ward: 'Ward 6', total: 19, resolved: 16 },
  { ward: 'Ward 7', total: 38, resolved: 24 },
  { ward: 'Ward 8', total: 29, resolved: 21 },
];

export const categoryStats = [
  { category: 'Roads & Potholes', count: 389, resolved: 298, color: '#3B82F6' },
  { category: 'Drainage', count: 267, resolved: 189, color: '#8B5CF6' },
  { category: 'Garbage', count: 312, resolved: 241, color: '#F59E0B' },
  { category: 'Streetlights', count: 156, resolved: 142, color: '#F97316' },
  { category: 'Water', count: 98, resolved: 67, color: '#06B6D4' },
  { category: 'Other', count: 62, resolved: 41, color: '#6B7280' },
];
