import { Issue } from './types';

export const issues: Issue[] = [
  {
    id: 'VNS-20481',
    title: 'Open drain near BHU Lanka Gate',
    category: 'Drainage',
    location: 'BHU Lanka Gate Road',
    ward: 'Ward 7 (Lanka / BHU)',
    mapX: 55, mapY: 38,
    lat: 25.2677, lng: 82.9913,
    status: 'in-progress',
    slaDuration: '24h',
    slaRemaining: '08h 32m',
    slaBreached: false,
    reportedDate: '2026-08-17',
    reportedTime: '09:14',
    department: 'Public Works Department',
    confirmations: 47,
    upvotes: 156,
    severity: 'high',
    description: 'Open drainage channel near BHU Lanka main gate causing foul smell and waterlogging on the pedestrian path. Multiple university students and citizens affected.',
    relatedReports: 4,
    reportedBy: 'Ramesh Chandra Verma',
  },
  {
    id: 'VNS-20476',
    title: 'Pothole on Varanasi Cantt Station Road',
    category: 'Roads & Potholes',
    location: 'Varanasi Cantt Station Road',
    ward: 'Ward 3 (Cantt)',
    mapX: 38, mapY: 32,
    lat: 25.3340, lng: 82.9900,
    status: 'pending',
    slaDuration: '48h',
    slaRemaining: '02h 15m',
    slaBreached: false,
    reportedDate: '2026-08-16',
    reportedTime: '14:30',
    department: 'PWD Roads Division',
    confirmations: 23,
    upvotes: 89,
    severity: 'medium',
    description: 'Large pothole approximately 2ft wide on Varanasi Cantt Station Road near the bus terminal junction causing vehicle damage and traffic congestion.',
    relatedReports: 2,
    reportedBy: 'Sunita Mishra',
  },
  {
    id: 'VNS-20471',
    title: 'Garbage accumulation near Cantt Civil Lines',
    category: 'Garbage',
    location: 'Cantt Civil Lines & Mall Road',
    ward: 'Ward 5 (Civil Lines)',
    mapX: 68, mapY: 22,
    lat: 25.3380, lng: 82.9850,
    status: 'sla-breached',
    slaDuration: '12h',
    slaRemaining: 'Breached',
    slaBreached: true,
    reportedDate: '2026-08-15',
    reportedTime: '07:45',
    department: 'Sanitation Division',
    confirmations: 61,
    upvotes: 234,
    severity: 'critical',
    description: 'Large garbage dump in front of Cantt Civil Lines park. Uncollected for over 3 days causing severe health hazard.',
    relatedReports: 6,
    reportedBy: 'Ajay Kumar Singh',
  },
  {
    id: 'VNS-20465',
    title: 'Broken streetlight near Chaudhary Charan Singh Bus Stand',
    category: 'Streetlights',
    location: 'Chaudhary Charan Singh Bus Stand, Cantt',
    ward: 'Ward 2 (Bus Stand Cantt)',
    mapX: 28, mapY: 52,
    lat: 25.3310, lng: 82.9870,
    status: 'resolved',
    slaDuration: '24h',
    slaRemaining: 'Resolved',
    slaBreached: false,
    reportedDate: '2026-08-14',
    reportedTime: '20:00',
    department: 'Electrical Division',
    confirmations: 18,
    upvotes: 45,
    severity: 'low',
    description: 'Street light pole near Cantt Bus Stand entrance not working for 3 days causing safety concerns at night.',
    relatedReports: 1,
    reportedBy: 'Priya Sharma',
  },
  {
    id: 'VNS-20459',
    title: 'Water leakage near Godowlia Market Junction',
    category: 'Water',
    location: 'Godowlia Chowk & Dashashwamedh Road',
    ward: 'Ward 4 (Dashashwamedh)',
    mapX: 48, mapY: 58,
    lat: 25.3090, lng: 83.0060,
    status: 'in-progress',
    slaDuration: '24h',
    slaRemaining: '14h 20m',
    slaBreached: false,
    reportedDate: '2026-08-13',
    reportedTime: '11:20',
    department: 'Jal Nigam',
    confirmations: 32,
    upvotes: 112,
    severity: 'high',
    description: 'Water pipe leakage at Godowlia Chowk junction near Dashashwamedh market causing road flooding and significant water waste.',
    relatedReports: 3,
    reportedBy: 'Vikash Dubey',
  },
  {
    id: 'VNS-20452',
    title: 'Road cave-in near Varanasi Collectorate, Kutchery',
    category: 'Roads & Potholes',
    location: 'Varanasi Collectorate Road, Kutchery',
    ward: 'Ward 1 (Kutchery)',
    mapX: 72, mapY: 15,
    lat: 25.3500, lng: 82.9800,
    status: 'assigned',
    slaDuration: '48h',
    slaRemaining: '28h 45m',
    slaBreached: false,
    reportedDate: '2026-08-18',
    reportedTime: '08:00',
    department: 'PWD Roads Division',
    confirmations: 12,
    upvotes: 67,
    severity: 'high',
    description: 'Significant road cave-in near Varanasi Collectorate & District Court office affecting two-way traffic.',
    relatedReports: 2,
    reportedBy: 'Mohan Lal Gupta',
  },
  {
    id: 'VNS-20448',
    title: 'Choked drainage near Sigra Stadium Area',
    category: 'Drainage',
    location: 'Sigra Stadium & Kashi Vidyapeeth Area',
    ward: 'Ward 8 (Sigra / Vidyapeeth)',
    mapX: 22, mapY: 68,
    lat: 25.3180, lng: 82.9880,
    status: 'pending',
    slaDuration: '24h',
    slaRemaining: '16h 10m',
    slaBreached: false,
    reportedDate: '2026-08-18',
    reportedTime: '10:30',
    department: 'Public Works Department',
    confirmations: 8,
    upvotes: 38,
    severity: 'medium',
    description: 'Drainage choked near Sigra Stadium causing waterlogging on Vidyapeeth Road after heavy rain.',
    relatedReports: 1,
    reportedBy: 'Kavita Tripathi',
  },
];

export const wardStats = [
  { ward: 'Ward 1 (Kutchery)', total: 18, resolved: 14 },
  { ward: 'Ward 2 (Cantt Bus Stand)', total: 25, resolved: 20 },
  { ward: 'Ward 3 (Cantt Railway Stn)', total: 31, resolved: 22 },
  { ward: 'Ward 4 (Dashashwamedh)', total: 22, resolved: 18 },
  { ward: 'Ward 5 (Cantt Civil Lines)', total: 45, resolved: 28 },
  { ward: 'Ward 6 (Chetganj / Bhelupur)', total: 19, resolved: 16 },
  { ward: 'Ward 7 (Lanka / BHU)', total: 38, resolved: 24 },
  { ward: 'Ward 8 (Sigra / Vidyapeeth)', total: 29, resolved: 21 },
];

export const categoryStats = [
  { category: 'Roads & Potholes', count: 389, resolved: 298, color: '#3B82F6' },
  { category: 'Drainage', count: 267, resolved: 189, color: '#8B5CF6' },
  { category: 'Garbage', count: 312, resolved: 241, color: '#F59E0B' },
  { category: 'Streetlights', count: 156, resolved: 142, color: '#F97316' },
  { category: 'Water', count: 98, resolved: 67, color: '#06B6D4' },
  { category: 'Other', count: 62, resolved: 41, color: '#6B7280' },
];

